import { describe, expect, it } from 'vitest';
import { prepareInput, filterReason, type RawFile } from './prepare.js';
import { redact, REDACTED } from './redact.js';

const f = (path: string, patch: string | null, status: RawFile['status'] = 'M'): RawFile => ({
  path, status, additions: 1, deletions: 0, patch,
});
const body = (n: number, tag = 'x') => `@@ -1 +1 @@\n${Array.from({ length: n }, (_, i) => `+${tag}${i} line of code`).join('\n')}\n`;

describe('redact', () => {
  const cases: [string, string][] = [
    ['aws', '+key = AKIAIOSFODNN7EXAMPLE'],
    ['github', '+t: ghp_' + 'a1B2c3D4e5F6g7H8i9J0k1L2m3N4o5P6q7R8'],
    ['github pat', '+github_pat_' + '11ABCDEFG0abcdefghij_' + 'x'.repeat(30)],
    ['anthropic', '+ANTHROPIC=sk-ant-api03-' + 'AbCdEf0123456789_-xyz'],
    ['bearer', '+Authorization: Bearer abcdefghijklmnop1234567890'],
    ['url', '+db = postgres://admin:hunter2pass@host/db'],
  ];
  for (const [name, text] of cases) {
    it(`redacts ${name}`, () => {
      const out = redact(text);
      expect(out).toContain(REDACTED);
      expect(out).not.toMatch(/AKIAIOSFODNN7EXAMPLE|ghp_a1B2|github_pat_11|sk-ant-api03|abcdefghijklmnop1234|hunter2pass/);
    });
  }
  it('redacts a PEM block inside a diff and keeps surrounding lines', () => {
    const pem = ['+-----BEGIN RSA PRIVATE KEY-----', '+MIIEowIBAAKCAQEAxyz', '+abcdEFGH1234', '+-----END RSA PRIVATE KEY-----', '+after = 1'].join('\n');
    const out = redact(`+before = 1\n${pem}\n`);
    expect(out).not.toContain('MIIEow');
    expect(out).not.toContain('abcdEFGH');
    expect(out).toContain('+before = 1');
    expect(out).toContain('+after = 1');
  });
  it('redacts secret assignments but keeps names and short values', () => {
    expect(redact('+password = "s3cr3tvalue99"')).toBe(`+password = "${REDACTED}"`);
    expect(redact('+const tokenCount = 5')).toBe('+const tokenCount = 5');
  });
  it('leaves ordinary code alone', () => {
    const s = '+function add(a, b) { return a + b; }\n';
    expect(redact(s)).toBe(s);
  });
  it('does not treat identifiers, calls or member access as secret values', () => {
    for (const s of [
      '+  author: commit.authorName,',
      '+  authorEmail = row.author_email',
      '+const tokenizer = createTokenizer(opts);',
      '+  const auth = requireAuth(req);',
      '+  passwordInput = document.querySelector("#pw")',
      '+  remaining = opt.tokenBudget;',
    ]) expect(redact(s)).toBe(s);
  });
  it('redacts env-style and JSON-style secret values', () => {
    expect(redact('+DB_PASSWORD=hunter2pass')).toBe(`+DB_PASSWORD=${REDACTED}`);
    expect(redact('+  "client_secret": "abc123def456ghi"')).toBe(`+  "client_secret": "${REDACTED}"`);
    expect(redact("+auth_token: 'zzzzyyyyxxxx'")).toBe(`+auth_token: '${REDACTED}'`);
  });
});

describe('filterReason', () => {
  it('classifies files', () => {
    expect(filterReason(f('pnpm-lock.yaml', body(1)))).toBe('lockfile');
    expect(filterReason(f('sub/Cargo.lock', body(1)))).toBe('lockfile');
    expect(filterReason(f('a.png', null, 'B'))).toBe('binary');
    expect(filterReason(f('node_modules/x/index.js', body(1)))).toBe('generated');
    expect(filterReason(f('web/app.min.js', body(1)))).toBe('generated');
    expect(filterReason(f('src/api.ts', '@@ -0,0 +1 @@\n+// @generated by tool\n'))).toBe('generated');
    expect(filterReason(f('src/a.ts', body(1)))).toBeNull();
  });
});

describe('prepareInput', () => {
  const change = (files: RawFile[]) => ({ repoName: 'r', title: 't', message: 'm', files });

  it('marks filtered files and drops their patch', () => {
    const p = prepareInput(change([f('yarn.lock', body(3)), f('a.ts', body(2))]));
    expect(p.input.files[0]).toMatchObject({ patch: null, filteredReason: 'lockfile' });
    expect(p.input.files[1]!.patch).not.toBeNull();
  });

  it('filters files over the size cap', () => {
    const p = prepareInput(change([f('big.ts', body(500))]), { maxFileBytes: 1000 });
    expect(p.input.files[0]).toMatchObject({ patch: null, filteredReason: 'too_large' });
  });

  it('respects the token budget, smallest first, truncating the next then dropping the rest', () => {
    const files = [f('big.ts', body(400)), f('small.ts', body(5)), f('mid.ts', body(100))];
    const p = prepareInput(change(files), { tokenBudget: 300 });
    const by = Object.fromEntries(p.input.files.map((x) => [x.path, x]));
    expect(by['small.ts']!.patch).not.toBeNull();
    expect(by['mid.ts']!.patch).toContain('truncated');
    expect(by['big.ts']).toMatchObject({ patch: null, filteredReason: 'too_large' });
    expect(p.truncated).toEqual(['mid.ts']);
    const total = p.input.files.reduce((n, x) => n + Math.ceil((x.patch ?? '').length / 4), 0);
    expect(total).toBeLessThanOrEqual(300);
    expect(p.input.files.map((x) => x.path)).toEqual(['big.ts', 'small.ts', 'mid.ts']);
  });

  it('is deterministic and hash reflects content and options', () => {
    const files = [f('a.ts', body(5)), f('b.ts', body(5, 'y'))];
    const a = prepareInput(change(files));
    const b = prepareInput(change(structuredClone(files)));
    expect(a.inputHash).toBe(b.inputHash);
    expect(a.inputHash).toMatch(/^[0-9a-f]{64}$/);
    expect(prepareInput(change(files), { tokenBudget: 10 }).inputHash).not.toBe(a.inputHash);
    expect(prepareInput(change([f('a.ts', body(6)), files[1]!])).inputHash).not.toBe(a.inputHash);
  });

  it('redacts before sending', () => {
    const p = prepareInput(change([f('a.ts', '@@ -0,0 +1 @@\n+k = "AKIAIOSFODNN7EXAMPLE"\n')]));
    expect(p.input.files[0]!.patch).not.toContain('AKIAIOSFODNN7EXAMPLE');
  });
});
